name: project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.4
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.8+4  # Add this for desktop support
  path: ^1.9.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.0  # Add this for path handling

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Billabong
      fonts:
        - asset: fonts/Billabong.otf